pygments: true
permalink: /:year/:month/:day/:title
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables",     "with_toc_data"]

rdiscount:
  extensions: [smart]
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]

title : I Will Servive
production_url : http://blog.restartr.com
description: "Ruby, Scala, Python, Golangとか"
disqus_shortname: ReSTARTR
analytics: UA-894530-10
gauges: #50f2b533613f5d7c8000000c
author :
  name : https://plus.google.com/103216164658230535238
  github : ReSTARTR
  twitter : ReSTARTR
  email: yoshida.masaki+restartr@gmail.com
